# Generated by Django 5.2.4 on 2025-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_address_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
